$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  filename: ./mcp-agent.log
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  rotate: true
  max_size: 10485760  # 10MB
  backup_count: 5

mcp:
  servers:
    fetch:
      command: "node"
      args: ["/home/bnoffke/mcp_servers/fetch-mcp/dist/index.js"]
    playwright:
      command: "xvfb-run"
      "args": ["-a","npx","-y", "@executeautomation/playwright-mcp-server"]
    puppeteer:
      command: "xvfb-run"
      args: ["-a","npx","-y", "@modelcontextprotocol/server-puppeteer"]
    markdownify:
      command: "node"
      args: ["/home/bnoffke/mcp_servers/markdownify-mcp/dist/index.js"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "/home/bnoffke/Documents/Resume"]
    mcp-pandoc:
      command: "poetry"
      args: ["run","uv","--directory","/home/bnoffke/mcp_servers/mcp-pandoc","run","mcp-pandoc"]
openai:
  default_model: gpt-4o-mini