$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  filename: ./mcp-agent.log
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  rotate: true
  max_size: 10485760  # 10MB
  backup_count: 5

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["run","mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "/home/bnoffke/Documents/Resume"]
    mcp-pandoc:
      command: "uv"
      args: ["--directory","/home/bnoffke/mcp_servers/mcp-pandoc","run","mcp-pandoc"]
openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4o-mini