$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  filename: ./mcp-agent.log
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  rotate: true
  max_size: 10485760  # 10MB
  backup_count: 5

mcp:
  servers:
    fetch:
      command: "node"
      args: ["/home/bnoffke/mcp_servers/fetch-mcp/dist/index.js"]
    markdownify:
      command: "node"
      args: ["/home/bnoffke/mcp_servers/markdownify-mcp/dist/index.js"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "/home/bnoffke/Documents/Resume"]
    markdown2pdf:
      command: "node"
      args: ["/home/bnoffke/mcp_servers/markdown2pdf-mcp/build/index.js"]
      "env": {
        "M2P_OUTPUT_DIR": "/home/bnoffke/Documents/Resume"
      }
openai:
  default_model: gpt-4o-mini